spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/SpringCloud_sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
eureka:
  client:
    service-url:
       defaultZone: http://localhost:8802/eureka/
server:
  port: 8081
profile:
   dev
env:
   test5
girl:
  name: mo2
  age: 29
